[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  POSTCSS_CONFIG = "postcss.config.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 